version: '3.8'

services:
  ml-explorer:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3101:3000"
    environment:
      - NODE_ENV=development
    volumes:
      - .:/app
      - /app/node_modules
    restart: unless-stopped